//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Catxx_prefab
    {
        public const string BundleName = "catxx_prefab";
        public const string CATXX = "catxx";
    }
    public class Catywm_prefab
    {
        public const string BundleName = "catywm_prefab";
        public const string CATYWM = "catywm";
    }
    public class Coinicon_spriteatlas
    {
        public const string BundleName = "coinicon_spriteatlas";
        public const string COINICON = "coinicon";
    }
    public class Herohg_prefab
    {
        public const string BundleName = "herohg_prefab";
        public const string HEROHG = "herohg";
    }
    public class Heroxt_prefab
    {
        public const string BundleName = "heroxt_prefab";
        public const string HEROXT = "heroxt";
    }
    public class Roomitem_spriteatlas
    {
        public const string BundleName = "roomitem_spriteatlas";
        public const string ROOMITEM = "roomitem";
    }
    public class Roomitemicon_spriteatlas
    {
        public const string BundleName = "roomitemicon_spriteatlas";
        public const string ROOMITEMICON = "roomitemicon";
    }
    public class Star_spriteatlas
    {
        public const string BundleName = "star_spriteatlas";
        public const string STAR = "star";
    }
    public class Uicatbreakpanel_prefab
    {
        public const string BundleName = "uicatbreakpanel_prefab";
        public const string UICATBREAKPANEL = "uicatbreakpanel";
    }
    public class Uicatinfoshowpanel_prefab
    {
        public const string BundleName = "uicatinfoshowpanel_prefab";
        public const string UICATINFOSHOWPANEL = "uicatinfoshowpanel";
    }
    public class Uicatitem_prefab
    {
        public const string BundleName = "uicatitem_prefab";
        public const string UICATITEM = "uicatitem";
    }
    public class Uicatpanel_prefab
    {
        public const string BundleName = "uicatpanel_prefab";
        public const string UICATPANEL = "uicatpanel";
    }
    public class Uicatpoolpanel_prefab
    {
        public const string BundleName = "uicatpoolpanel_prefab";
        public const string UICATPOOLPANEL = "uicatpoolpanel";
    }
    public class Uicatskinpanel_prefab
    {
        public const string BundleName = "uicatskinpanel_prefab";
        public const string UICATSKINPANEL = "uicatskinpanel";
    }
    public class Uicattrainitem_prefab
    {
        public const string BundleName = "uicattrainitem_prefab";
        public const string UICATTRAINITEM = "uicattrainitem";
    }
    public class Uicattrainpanel_prefab
    {
        public const string BundleName = "uicattrainpanel_prefab";
        public const string UICATTRAINPANEL = "uicattrainpanel";
    }
    public class Uidrinkspanel_prefab
    {
        public const string BundleName = "uidrinkspanel_prefab";
        public const string UIDRINKSPANEL = "uidrinkspanel";
    }
    public class Uiexplorecatitem_prefab
    {
        public const string BundleName = "uiexplorecatitem_prefab";
        public const string UIEXPLORECATITEM = "uiexplorecatitem";
    }
    public class Uiexplorecatpanel_prefab
    {
        public const string BundleName = "uiexplorecatpanel_prefab";
        public const string UIEXPLORECATPANEL = "uiexplorecatpanel";
    }
    public class Uiexploremapnode_prefab
    {
        public const string BundleName = "uiexploremapnode_prefab";
        public const string UIEXPLOREMAPNODE = "uiexploremapnode";
    }
    public class Uiexplorepanel_prefab
    {
        public const string BundleName = "uiexplorepanel_prefab";
        public const string UIEXPLOREPANEL = "uiexplorepanel";
    }
    public class Uiexploretaskpanel_prefab
    {
        public const string BundleName = "uiexploretaskpanel_prefab";
        public const string UIEXPLORETASKPANEL = "uiexploretaskpanel";
    }
    public class Uiexploreteampanel_prefab
    {
        public const string BundleName = "uiexploreteampanel_prefab";
        public const string UIEXPLORETEAMPANEL = "uiexploreteampanel";
    }
    public class Uifacilitiesinfopanel_prefab
    {
        public const string BundleName = "uifacilitiesinfopanel_prefab";
        public const string UIFACILITIESINFOPANEL = "uifacilitiesinfopanel";
    }
    public class Uifaciteminfopanel_prefab
    {
        public const string BundleName = "uifaciteminfopanel_prefab";
        public const string UIFACITEMINFOPANEL = "uifaciteminfopanel";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "uihomepanel";
    }
    public class Uiroominfopanel_prefab
    {
        public const string BundleName = "uiroominfopanel_prefab";
        public const string UIROOMINFOPANEL = "uiroominfopanel";
    }
    public class Uiroomitem1panel_prefab
    {
        public const string BundleName = "uiroomitem1panel_prefab";
        public const string UIROOMITEM1PANEL = "uiroomitem1panel";
    }
    public class Uiroomitem2panel_prefab
    {
        public const string BundleName = "uiroomitem2panel_prefab";
        public const string UIROOMITEM2PANEL = "uiroomitem2panel";
    }
    public class Uiroomitem3panel_prefab
    {
        public const string BundleName = "uiroomitem3panel_prefab";
        public const string UIROOMITEM3PANEL = "uiroomitem3panel";
    }
    public class Uiroomitem4panel_prefab
    {
        public const string BundleName = "uiroomitem4panel_prefab";
        public const string UIROOMITEM4PANEL = "uiroomitem4panel";
    }
    public class Uiroomitem5panel_prefab
    {
        public const string BundleName = "uiroomitem5panel_prefab";
        public const string UIROOMITEM5PANEL = "uiroomitem5panel";
    }
    public class Uiroomitem6panel_prefab
    {
        public const string BundleName = "uiroomitem6panel_prefab";
        public const string UIROOMITEM6PANEL = "uiroomitem6panel";
    }
    public class Uiroomitem7panel_prefab
    {
        public const string BundleName = "uiroomitem7panel_prefab";
        public const string UIROOMITEM7PANEL = "uiroomitem7panel";
    }
    public class Uiroomitem8panel_prefab
    {
        public const string BundleName = "uiroomitem8panel_prefab";
        public const string UIROOMITEM8PANEL = "uiroomitem8panel";
    }
    public class Uiroomitem9panel_prefab
    {
        public const string BundleName = "uiroomitem9panel_prefab";
        public const string UIROOMITEM9PANEL = "uiroomitem9panel";
    }
    public class Uiroomitem10panel_prefab
    {
        public const string BundleName = "uiroomitem10panel_prefab";
        public const string UIROOMITEM10PANEL = "uiroomitem10panel";
    }
    public class Uiroomiteminfopanel_prefab
    {
        public const string BundleName = "uiroomiteminfopanel_prefab";
        public const string UIROOMITEMINFOPANEL = "uiroomiteminfopanel";
    }
    public class Uiroomtaskinfopanel_prefab
    {
        public const string BundleName = "uiroomtaskinfopanel_prefab";
        public const string UIROOMTASKINFOPANEL = "uiroomtaskinfopanel";
    }
    public class Uiroomunlockpanel_prefab
    {
        public const string BundleName = "uiroomunlockpanel_prefab";
        public const string UIROOMUNLOCKPANEL = "uiroomunlockpanel";
    }
    public class Uiroomupdatebtn_prefab
    {
        public const string BundleName = "uiroomupdatebtn_prefab";
        public const string UIROOMUPDATEBTN = "uiroomupdatebtn";
    }
    public class Uiroomupdatebuypanel_prefab
    {
        public const string BundleName = "uiroomupdatebuypanel_prefab";
        public const string UIROOMUPDATEBUYPANEL = "uiroomupdatebuypanel";
    }
    public class Uiroomupdateinfopanel_prefab
    {
        public const string BundleName = "uiroomupdateinfopanel_prefab";
        public const string UIROOMUPDATEINFOPANEL = "uiroomupdateinfopanel";
    }
    public class Uiroomupdateitempanel_prefab
    {
        public const string BundleName = "uiroomupdateitempanel_prefab";
        public const string UIROOMUPDATEITEMPANEL = "uiroomupdateitempanel";
    }
    public class Uisummoninfopanel_prefab
    {
        public const string BundleName = "uisummoninfopanel_prefab";
        public const string UISUMMONINFOPANEL = "uisummoninfopanel";
    }
    public class Uitippanel_prefab
    {
        public const string BundleName = "uitippanel_prefab";
        public const string UITIPPANEL = "uitippanel";
    }
    public class Uiworkcatitem_prefab
    {
        public const string BundleName = "uiworkcatitem_prefab";
        public const string UIWORKCATITEM = "uiworkcatitem";
    }
    public class Uiworkcatpanel_prefab
    {
        public const string BundleName = "uiworkcatpanel_prefab";
        public const string UIWORKCATPANEL = "uiworkcatpanel";
    }
}
